title: >-
  Antonio Trento, theme Jeky New Age, the start Bootstrap themplate build for
  jekyll
email: null
description: 'A jekyll template for landing pages, portfolio and blogging'
baseurl: ''
url: ''
data-ad-slot: null
data-ad-client: null
google_ad_client: null
google_analytics: null
addthis_id: null
disqus_account: null
social:
  - title: twitter
    url: 'https://twitter.com/lantoniotrento'
  - title: facebook
    url: 'https://facebook.com/lantoniotrento'
  - title: google-plus
    url: 'https://plus.google.com/+AntoniotrentoIt'
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
gems:
  - jekyll-paginate
  - jekyll-feed
